#define TRUE        1
#define FALSE       0

typedef int             BOOL;

typedef unsigned char   BYTE, *LPBYTE, UCHAR, *PUCHAR;
typedef unsigned int    USHORT, *PUSHORT;
typedef unsigned long   ULONG, *PULONG;

typedef unsigned short  WORD, *PWORD;
typedef unsigned long   DWORD, *PDWORD;

typedef signed      char        INT8;
typedef unsigned    char        UINT8;
typedef signed      short       INT16;
typedef unsigned    short       UINT16;
typedef signed      int         INT32;
typedef unsigned    int         UINT32;
